# Generated by Django 2.0.2 on 2018-02-25 10:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('ashdod', django.db.models.manager.Manager()),
            ],
        ),
    ]
